<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <AssemblyName>SupplyDrop</AssemblyName>
    <RootNamespace>SupplyDrop</RootNamespace>
    <UseAugatonLib>true</UseAugatonLib>
    <Version>4.0.0</Version>
    <Configurations>Debug;Release</Configurations>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <DebugType Condition=" '$(Configuration)' == 'Release' ">none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ExMod.Exiled" Version="9.14.2" PrivateAssets="all" ExcludeAssets="runtime" />
  </ItemGroup>

</Project>
